name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Run unit tests
      #   run: |
      #     # Ajusta el comando según tu framework de pruebas
      #     python -m unittest discover

      - name: Build Docker image
        run: docker build -t backend-app .

      - name: Save Docker image as artifact
        run: docker save backend-app | gzip > backend-app.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-docker-image
          path: backend-app.tar.gz